# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MPConfig
                                 A QGIS plugin
 This plugin provides a data structure to create, config and maintain a Masterportal.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-26
        copyright            : (C) 2026 by Christoph Jung
        email                : jagodki.cj@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Christoph Jung'
__date__ = '2026-03-26'
__copyright__ = '(C) 2026 by Christoph Jung'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterProviderConnection,
                       QgsProviderRegistry)
from pathlib import Path
import os, re
from qgis.PyQt.QtCore import QVariant
from qgis.core import (
    QgsField,
    QgsFields,
    QgsVectorFileWriter,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransformContext,
    QgsWkbTypes
)

class DataStructureAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    
    CONNECTION = 'CONNECTION'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(
            QgsProcessingParameterProviderConnection(
                self.CONNECTION,
                self.tr('Geopackage Connection'),
                provider='ogr',
                optional=False
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        
        # extract the connection parameter and get the absolute path of the geopackage file
        gpkg_connection_name = self.parameterAsString(parameters, self.CONNECTION, context)
        metadata = QgsProviderRegistry.instance().providerMetadata("ogr")
        connection = metadata.findConnection(gpkg_connection_name)
        uri = connection.uri()
        gpkg_path = re.split(r"\|", uri)[0]
        
        # get the schema file path
        schema_file = os.path.abspath(os.path.join(os.path.dirname( __file__ ), '..', 'config', 'er_chart.js'))

        
        schema = self.parse_er_file(schema_file)

        self.create_schema_in_gpkg(gpkg_path, schema)
        
        
        # (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                # context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        # total = 100.0 / source.featureCount() if source.featureCount() else 0
        # features = source.getFeatures()

        # for current, feature in enumerate(features):
            # # Stop the algorithm if cancel button has been clicked
            # if feedback.isCanceled():
                # break

            # # Add a feature in the sink
            # sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # # Update the progress bar
            # feedback.setProgress(int(current * total))

        # # Return the results of the algorithm. In this case our only result is
        # # the feature sink which contains the processed features, but some
        # # algorithms may return multiple feature sinks, calculated numeric
        # # statistics, etc. These should all be included in the returned
        # # dictionary, with keys matching the feature corresponding parameter
        # # or output names.
        # return {self.OUTPUT: dest_id}
        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'create_data_structure'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return 'Create Data Structure'

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return 'Data Structure'

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'data_structure'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DataStructureAlgorithm()
    
    def qvariant_type(self, field_type):

        field_type = field_type.lower()

        mapping = {
            "string": QVariant.String,
            "json": QVariant.String,
            "boolean": QVariant.Bool,
            "int": QVariant.Int,
            "integer": QVariant.Int,
            "float": QVariant.Double,
            "double": QVariant.Double
        }

        return mapping.get(field_type, QVariant.String)

    def create_table_in_gpkg(self, gpkg_path, table_name, field_definitions):

        fields = QgsFields()

        for field_name, field_type, is_pk, is_fk in field_definitions:

            fields.append(
                QgsField(
                    field_name,
                    self.qvariant_type(field_type)
                )
            )

        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = "GPKG"
        options.layerName = table_name
        options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer

        writer = QgsVectorFileWriter.create(
            gpkg_path,
            fields,
            QgsWkbTypes.NoGeometry,
            QgsCoordinateReferenceSystem(),
            QgsCoordinateTransformContext(),
            options
        )

        if writer.hasError() != QgsVectorFileWriter.NoError:
            raise Exception(writer.errorMessage())

        del writer
    
    def create_schema_in_gpkg(self, gpkg_path, schema):

        first_table = True

        for table_name, fields in schema.items():

            self.create_table_in_gpkg(
                gpkg_path,
                table_name,
                fields
            )

            first_table = False
    
    def parse_er_file(self, file_path):
        """
        Liest die Mermaid-ER-Datei ein.

        Ergebnis:
        {
            "PORTAL_CONFIG": [
                ("id", "int", True, False),
                ("title", "string", False, False),
                ...
            ]
        }
        """

        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        tables = {}

        table_pattern = r'([A-Z_][A-Z0-9_]*)\s*\{(.*?)\}'
        matches = re.findall(table_pattern, content, re.DOTALL)

        for table_name, body in matches:

            fields = []

            for line in body.splitlines():

                line = line.strip()

                if not line:
                    continue

                parts = line.split()

                if len(parts) < 2:
                    continue

                field_type = parts[0]
                field_name = parts[1]

                is_pk = "PK" in parts
                is_fk = "FK" in parts

                fields.append(
                    (
                        field_name,
                        field_type,
                        is_pk,
                        is_fk
                    )
                )

            tables[table_name] = fields

        return tables