# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MPConfig
                                 A QGIS plugin
 This plugin provides a data structure to create, config and maintain a Masterportal.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-26
        copyright            : (C) 2026 by Christoph Jung
        email                : jagodki.cj@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Christoph Jung'
__date__ = '2026-03-26'
__copyright__ = '(C) 2026 by Christoph Jung'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MPConfig class from file MPConfig.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mp_config import MPConfigPlugin
    return MPConfigPlugin()
